import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import React from "react";
import { useContentById } from "../../services/content/use-content-detail";
import parse from "html-react-parser";
import DOMPurify from "dompurify";

export default function ActivityDetail() {
  const router = useRouter();
  const { slug } = router?.query;
  const { data } = useContentById(slug);
  const contentData = data?.data;
  return (
    <div>
      <Head>
        <title>Aktivitas - Gooddreamer Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-8 px-20">
        <Image
          src={contentData?.image}
          width={1140}
          height={285}
          alt="content-image"
          className="rounded-[10px] w-full h-[285px] object-cover"
        />
        <h1 className="text-[40px] text-purple-primary font-bold mt-14">
          {contentData?.title}
        </h1>
        <div className="mt-8">
          {contentData?.content &&
            parse(
              // DOMPurify.sanitize(
              contentData?.content
                ?.replaceAll("<p", "<br/><p")
                ?.replaceAll("<hr", "<br/><hr")
                .replaceAll("<h1", "<br/><h1")
                .replaceAll("<h2", "<br/><h2")
                .replaceAll("<h3", "<br/><h3")
                .replaceAll("<ul", `<ul style="list-style-type: disc;" `)
              // )
            )}
        </div>
      </main>
    </div>
  );
}
