import Head from "next/head";
import Image from "next/image";
import { Hero } from "../../components/Hero";
import { Card } from "../../ui/Card";

export default function ActivityPage() {
  return (
    <div>
      <Head>
        <title>Aktivitas - Gooddreamer Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Hero />
        <div className=" py-8 px-20 mt-14">
          <div className="flex justify-between">
            <h1 className="text-[40px] text-purple-primary font-bold">
              Event dan Komunitas GDSquad
            </h1>
          </div>
        </div>
        <div className="grid grid-cols-3 gap-12 py-4 px-20 mt-4">
          {Array.from({ length: 9 }).map(() => (
            <Card
              withDetailButton
              image="/assets/images/dummyevent.png"
              title="test"
              content="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
            />
          ))}
        </div>
      </main>
    </div>
  );
}
