import Head from "next/head";
import Image from "next/image";
import { Hero } from "../../components/Hero";
import { useActivityList } from "../../services/content/use-content-list";
import { Card } from "../../ui/Card";

export default function ActivityPage() {
  const { data } = useActivityList();
  const activities = data?.data;

  return (
    <div>
      <Head>
        <title>Aktivitas - Gooddreamer Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Hero />
        <div className=" py-8 px-20 mt-14">
          <div className="flex justify-between">
            <h1 className="text-[40px] text-purple-primary font-bold">
              Event dan Komunitas GDSquad
            </h1>
          </div>
        </div>
        <div className="grid grid-cols-3 gap-12 py-4 px-20 mt-4">
          {activities &&
            activities?.map((activity: any) => (
              <Card
                withDetailButton
                image={activity?.thumbnail}
                title={activity?.title}
                content={activity?.content_preview}
                url={`/activity/${activity?.uri}`}
              />
            ))}
        </div>
      </main>
    </div>
  );
}
