import Head from "next/head";
import Image from "next/image";
import React from "react";
import { Hero } from "../../components/Hero";
import { faqDummy } from "../../constants/faqDummy";
import { Card } from "../../ui/Card";

export default function FAQPage() {
  const [selectedFaqIndex, setSelectedFaqIndex] = React.useState(0);

  const onClickFaqIndex = (index: number) => {
    setSelectedFaqIndex(index);
  };

  return (
    <div>
      <Head>
        <title>FAQ - Gooddreamer Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className=" py-8 px-20 mt-4">
          <div className="flex justify-between">
            <h1 className="text-[40px] text-purple-primary font-bold">FAQ</h1>
          </div>
        </div>
        <div className="flex py-2 px-20 mt-4">
          <div className="w-1/2">
            <div className="relative">
              <input
                type="text"
                className="h-[60px] pl-12 w-full rounded-[8px] text-[14px] placeholder:text-[14px] text-grey-sixth px-[12px] py-[5px] bg-grey-fifth focus:outline-none"
                placeholder="Cari topik pertanyaan terkait"
              />
              <Image
                src="/assets/icons/magnifying-glass.svg"
                width={23}
                height={23}
                alt="magnifying"
                className="absolute left-4 transform -translate-y-1/2 top-1/2"
              />
            </div>
          </div>
        </div>
        <div className="flex pt-2 pb-8 gap-8 px-20 mt-4">
          <div className="bg-purple-primary p-4 text-white rounded-[5px] text-[20px] w-1/2 h-screen">
            <ul className="flex flex-col gap-4 list-disc list-inside">
              {faqDummy?.map((val, index) => (
                <li
                  onClick={() => onClickFaqIndex(index)}
                  className={`transition-all  cursor-pointer p-4 rounded-[5px] ${
                    selectedFaqIndex === index ? "bg-purple-third" : ""
                  }`}
                >
                  {val?.title}
                </li>
              ))}
            </ul>
          </div>
          <div className="w-1/2 p-4">
            <h1 className="text-[30px] font-bold leading-[40px]">
              {faqDummy[selectedFaqIndex]?.title}
            </h1>
            <p className="mt-4">{faqDummy[selectedFaqIndex]?.createdAt}</p>
            <div
              className="mt-4"
              dangerouslySetInnerHTML={{
                __html: faqDummy[selectedFaqIndex]?.content,
              }}
            />{" "}
            <div className="flex items-center gap-4 mt-12">
              <button className="w-[200px] justify-center rounded-[8px] bg-[#F7F7F7] px-[12px] py-[10px] text-[14px] text-[#BDBDBD] flex items-center gap-2">
                <Image
                  src="/assets/icons/thumb.svg"
                  width={20}
                  height={20}
                  alt="thumb"
                />
                <span>Membantu</span>
              </button>
              <button className="w-[200px] justify-center rounded-[8px] bg-[#F7F7F7] px-[12px] py-[10px] text-[14px] text-[#BDBDBD] flex items-center gap-2">
                <Image
                  src="/assets/icons/down-thumb.svg"
                  width={20}
                  height={20}
                  alt="down-thumb"
                />
                <span>Tidak Membantu</span>
              </button>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
