import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import React from "react";
import { useContentById } from "../../services/content/use-content-detail";

export default function ArticleDetail() {
  const router = useRouter();
  const { slug } = router?.query;
  const { data } = useContentById(slug);
  const contentData = data?.data;
  return (
    <div>
      <Head>
        <title>Artikel - Gooddreamer Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-8 px-20">
        <Image
          src={contentData?.image}
          width={1140}
          height={285}
          alt="content-image"
          className="rounded-[10px] w-full h-[285px] object-cover"
        />
        <h1 className="text-[40px] text-purple-primary font-bold mt-14">
          {contentData?.title}
        </h1>
        <div
          className="mt-8"
          dangerouslySetInnerHTML={{ __html: contentData?.content }}
        />
      </main>
    </div>
  );
}
