import Head from "next/head";
import React from "react";
import { Card } from "../../ui/Card";

export default function ArticlePage() {
  return (
    <div>
      <Head>
        <title>Artikel - Gooddreamer Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className="py-8 px-20 mt-14">
          <div className="flex justify-between">
            <h1 className="text-[40px] text-purple-primary font-bold">
              Gooddreamer Artikel
            </h1>
          </div>
          <div className="flex gap-12 mt-8">
            <div className="w-3/4">
              <Card
                coverHeight="h-[400px]"
                image="/assets/images/dummyevent.png"
                title="test"
                content="Lorem Ipsum is simply dummy text of the printing and typesetting industry. "
              />
            </div>
            <div className="w-1/4">
              <Card
                withDetailButton
                image="/assets/images/dummyevent.png"
                title="test"
                content="Lorem Ipsum is simply dummy text of the printing and typesetting industry."
              />
            </div>
          </div>
          <div className="grid grid-cols-3 gap-12 mt-12">
            <Card
              withDetailButton
              image="/assets/images/dummyevent.png"
              title="test"
              content="Lorem Ipsum is simply dummy text of the printing and typesetting industry."
            />
            <Card
              withDetailButton
              image="/assets/images/dummyevent.png"
              title="test"
              content="Lorem Ipsum is simply dummy text of the printing and typesetting industry."
            />
            <Card
              withDetailButton
              image="/assets/images/dummyevent.png"
              title="test"
              content="Lorem Ipsum is simply dummy text of the printing and typesetting industry."
            />
          </div>

          <div className="flex gap-12 mt-8">
            <div className="w-3/4">
              <Card
                coverHeight="h-[400px]"
                image="/assets/images/dummyevent.png"
                title="test"
                content="Lorem Ipsum is simply dummy text of the printing and typesetting industry. "
              />
            </div>
            <div className="w-1/4">
              <Card
                withDetailButton
                image="/assets/images/dummyevent.png"
                title="test"
                content="Lorem Ipsum is simply dummy text of the printing and typesetting industry."
              />
            </div>
          </div>
          <div className="grid grid-cols-3 gap-12 mt-12">
            <Card
              withDetailButton
              image="/assets/images/dummyevent.png"
              title="test"
              content="Lorem Ipsum is simply dummy text of the printing and typesetting industry."
            />
            <Card
              withDetailButton
              image="/assets/images/dummyevent.png"
              title="test"
              content="Lorem Ipsum is simply dummy text of the printing and typesetting industry."
            />
            <Card
              withDetailButton
              image="/assets/images/dummyevent.png"
              title="test"
              content="Lorem Ipsum is simply dummy text of the printing and typesetting industry."
            />
          </div>
        </div>
      </main>
    </div>
  );
}
