import Head from "next/head";
import Image from "next/image";
import { Announcement } from "../components/Announcement";
import { Article } from "../components/Article";
import { Author } from "../components/Author";
import { Event } from "../components/Event";
import { Faq } from "../components/Faq";
import { Hero } from "../components/Hero";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Gooddreamer Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Hero />
        <Announcement />
        <Event />
        <Author />
        <Article />
        <Faq />
      </main>
    </div>
  );
}
